apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_USER: 'postgres'
  POSTGRES_DB: "hive"
  POSTGRES_PASSWORD: "postgres"
  HOST: "postgresdb.default"
  PORT: "5432"